import { type Metadata } from "next";

export const metadata: Metadata = {
    title: "Product Page",
    description: "Generated by disorganized",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function ProductLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>
};